package com.qihoo.finance.lowcode.console.completion;

import com.google.common.collect.Lists;
import com.intellij.codeInsight.lookup.LookupElementBuilder;
import com.intellij.ui.JBColor;

import java.awt.*;
import java.util.List;

/**
 * SQLCompletionKeywords
 *
 * @author fengjinfu-jk
 * date 2023/9/14
 * @version 1.0.0
 * @apiNote SQLCompletionKeywords
 */
public interface CompletionKeywords {
    Color keywordColor = new JBColor(new Color(182, 119, 49), new Color(182, 119, 49));
    Color mongoKeywordColor = JBColor.CYAN;

    List<LookupElementBuilder> MongoLookup = Lists.newArrayList(
            LookupElementBuilder.create("db").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("insert").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("insertOne").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("insertMany").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("update").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("remove").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("find").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("pretty").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sort").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("limit").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("skip").withItemTextForeground(mongoKeywordColor).withTypeText("keyword"),

            LookupElementBuilder.create("$all").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$and").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$bitsAllClear").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$bitsAllSet").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$comment").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$elemMatch").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$eq").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$exists").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$expr").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$geoIntersects").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$geoWithin").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$gt").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$gte").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$in").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$jsonSchema").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$lt").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$lte").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$mod").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$ne").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$near").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$nearSphere").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$nin").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$nor").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$not").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$or").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$regex").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$size").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$slice").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$text").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$type").withItemTextForeground(mongoKeywordColor).withTypeText("query"),
            LookupElementBuilder.create("$where").withItemTextForeground(mongoKeywordColor).withTypeText("query"),

            LookupElementBuilder.create("$addFields").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$bucket").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$bucketAuto").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$collStats").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$count").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$facet").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$geoNear").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$graphLookup").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$group").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$indexStats").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$limit").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$lookup").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$match").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$out").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$project").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$redact").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$replaceRoot").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$sample").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$skip").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$sort").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$sortByCount").withItemTextForeground(mongoKeywordColor).withTypeText("stage"),
            LookupElementBuilder.create("$unwind").withItemTextForeground(mongoKeywordColor).withTypeText("stage")
    );
    List<LookupElementBuilder> MysqlLookup = Lists.newArrayList(
            LookupElementBuilder.create("bit ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("tinyint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bool ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("boolean ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("smallint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mediumint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("integer ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bigint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("double precision ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("double ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("real ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("float ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("decimal ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dec ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("numeric ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("fixed ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("date ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("datetime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("timestamp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("time ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("year ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("varchar ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("national varchar ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("binary ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("varbinary ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("tinyblob ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("tinytext ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("blob ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("text ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mediumblob ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mediumtext ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("longblob ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("longtext ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("enum ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("accessible ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("add ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("algorithm ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("all ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("alter ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("analyze ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("and ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("as ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("asc ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("asensitive ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("before ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("between ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("both ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("by ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("call ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cascade ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cascaded ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("case ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("change ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("character ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("check ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("close ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("collate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("column ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("columns ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("concurrent ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("condition ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("constraint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("continue ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("convert ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("create ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cross ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("current_user ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cursor ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("data ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("database ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("databases ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("declare ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("default ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("definer ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("delayed ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("delete ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("desc ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("describe ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("deterministic ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("distinct ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("distinctrow ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("div ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("do ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("drop ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dual ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dumpfile ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("duplicate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("each ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("else ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("elseif ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("enclosed ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("end ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("escaped ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("exists ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("exit ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("expansion ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("explain ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("fetch ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("fields ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("first ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("float4 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("float8 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("for ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("force ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("foreign ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("from ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("fulltext ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("grant ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("group ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("handler ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("having ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("high_priority ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("if ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ignore ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("in ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("index ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("infile ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("inner ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("inout ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("insensitive ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("insert ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int1 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int2 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int3 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int4 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("int8 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("interval ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("into ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("invoker ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("is ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("iterate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("join ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("key ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("keys ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("kill ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("language ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("last ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("leading ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("leave ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("left ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("level ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("like ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("limit ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("linear ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("lines ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("load ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("local ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("lock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("long ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("loop ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("low_ignore ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("low_priority ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("master_ssl_verify_server_cert ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("match ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("merge ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("middleint ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mod ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mode ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("modifies ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("natural ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("next ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("no_write_to_binlog ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("not ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("null ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("offset ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("oj ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("on ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("open ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("optimize ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("option ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("optionally ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("or ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("order ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("out ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("outer ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("outfile ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("precision ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("prev ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("primary ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("procedure ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("purge ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("query ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("quick ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("range ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("read ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("read_only ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("read_write ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("reads ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("references ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("regexp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("release ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rename ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("repeat ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("replace ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("require ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("restrict ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("return ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("reverse ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("revoke ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("right ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rlike ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rollup ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("schema ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("schemas ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("security ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("select ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sensitive ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("separator ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("set ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("share ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("show ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("spatial ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("specific ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_big_result ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_buffer_result ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_cache ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_calc_found_rows ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_no_cache ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sql_small_result ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sqlexception ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sqlstate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sqlwarning ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ssl ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("starting ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("straight_join ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("table ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("temptable ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("terminated ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("then ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("to ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("trailing ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("trigger ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("truncate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("undefined ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("undo ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("union ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("unique ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("unlock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("unsigned ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("update ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("usage ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("use ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("using ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("value ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("values ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("varcharacter ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("varying ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("view ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("when ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("where ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("while ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("with ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("write ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("xor ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("zerofill ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("false ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("true ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("abs ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("acos ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("adddate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("addtime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("aes_decrypt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("aes_encrypt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("against ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ascii ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("asin ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("atan ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("atan2 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("avg ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("benchmark ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bin ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bit_and ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bit_length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bit_or ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("bit_xor ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ceil ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ceiling ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("char ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("char_length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("character_length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("charset ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("coercibility ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("collation ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("compress ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("concat ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("concat_ws ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("connection_id ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("conv ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("convert_tz ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cos ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("cot ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("count ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("crc32 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("curdate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("current_date ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("current_time ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("current_timestamp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("curtime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("date_add ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("date_format ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("date_sub ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("datediff ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("day ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("day_hour ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("day_microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("day_minute ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("day_second ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dayname ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dayofmonth ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dayofweek ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("dayofyear ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("decode ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("degrees ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("des_decrypt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("des_encrypt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("elt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("encode ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("encrypt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("exp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("export_set ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("extract ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("field ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("find_in_set ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("floor ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("fn_second_microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("format ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("found_rows ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("from_days ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("from_unixtime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("get_format ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("get_lock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("group_concat ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("hex ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("hour ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("hour_microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("hour_minute ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("hour_second ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ifnull ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("inet_aton ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("inet_ntoa ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("instr ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("is_free_lock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("is_used_lock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("last_day ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("last_insert_id ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("lcase ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ln ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("load_file ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("localtime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("localtimestamp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("locate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("log ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("log10 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("log2 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("lower ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("lpad ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ltrim ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("make_set ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("makedate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("maketime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("master_pos_wait ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("max ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("md5 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("mid ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("min ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("minute ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("minute_microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("minute_second ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("month ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("monthname ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("name_const ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("not_like ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("not_regexp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("now ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("nullif ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("oct ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("octet_length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("old_password ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ord ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("password ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("period_add ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("period_diff ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("pi ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("position ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("pow ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("power ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("quarter ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("quote ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("radians ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rand ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("release_lock ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("round ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("row_count ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rpad ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("rtrim ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sec_to_time ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("second ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("second_microsecond ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("session_user ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sha ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sha1 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sha2 ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sign ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sin ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sleep ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("soundex ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sounds_like ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("space ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sqrt ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("std ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("stddev ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("stddev_pop ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("stddev_samp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("str_to_date ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("strcmp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("subdate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("substr ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("substring ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("substring_index ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("subtime ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sum ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("sysdate ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("system_user ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("tan ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("time_format ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("time_to_sec ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("timediff ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("timestampadd ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("timestampdiff ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("to_days ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("trim ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("ucase ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("uncompress ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("uncompressed_length ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("unhex ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("unix_timestamp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("upper ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("user ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("utc_date ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("utc_time ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("utc_timestamp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("uuid ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("uuid_short ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("var_pop ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("var_samp ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("variance ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("version ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("week ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("weekday ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("weekofyear ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("weight_string ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("year_month ").withItemTextForeground(keywordColor).withTypeText("keyword"),
            LookupElementBuilder.create("yearweek")
    );
}
